language: node_js
node_js:
  - "node"
before_install:
  - git config --global user.email "s.bosch@unesco.org"
  - git config --global user.name "TRAVIS CI"
  - git config --global credential.helper "store --file=/home/travis/credentials"
  - echo "https://${GH_TOKEN}:@github.com" > /home/travis/credentials
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'

