language: node_js
node_js:
  - "node"
before_install:
  - git config credential.helper "store --file=.git/credentials"; echo "https://obis-system:${GH_TOKEN}@github.com" > .git/credentials 2>/dev/null
  - git config --global user.email "s.bosch@unesco.org"
  - git config --global user.name "Samuel Bosch"
deploy:
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
after_failure:
  - cat /home/travis/.npm/_logs/*.log
